import docstree from "../../Assets/Projects/docs-tree.png";
import aorforms from "../../Assets/Projects/aorforms.png";
import iluy from "../../Assets/Projects/iluy.png";
import hewantsbarber from "../../Assets/Projects/hewantsbarber.png";
import reboucasofficial from "../../Assets/Projects/reboucasofficial.png";
import araujocabral from "../../Assets/Projects/araujocabral.png";
import pabloitalo from "../../Assets/Projects/pabloitalo.png";
import personaltrainer from "../../Assets/Projects/personaltrainer.png";
import shop from "../../Assets/Projects/shop.png";



export const alldata = [
    {
        language:'US',
  
        navbar1:'Home',
        navbar2:'About',
        navbar3:'Projects',
        navbar4:'Resume',
  
        footer1:'Pablo Ítalo, Senior Software Engineer',
        footer2:`Copyright © 2018 - ${new Date().getFullYear()} Pablo Italo`,
  
        home1:'Hi There!',
        home2:"I'M",
        home3:"Senior Software Engineer",
        home4:"LET ME",
        home5:"INTRODUCE",
        home6:"MYSELF",
        home7:"I fell in love with programming and I have learned a great deal.",
        home8:"I am proficient in modern languages and frameworks such as",
        home9:"Next.js, Nest.js, React, React Native, Node.js, Express, TypeScript, and JavaScript.",
        home10:"Additionally, I have experience with Python, Django, PHP, WordPress, PostgreSQL, MongoDB, Redis, and more.",
        home11:"My field of interest lies in developing innovative",
        home12:"Web and Mobile Technologies and varied solutions.",
        home13:"FIND ME ON",
        home14:"Feel free to",
        home15:"connect",
        home16:"with me",
  
        about1:"Know Who",
        about2:"I Am",
        about3:"Hello everyone, I'm",
        about4:"Pablo Ítalo",
        about5:", a",
        about6:"Senior Software Engineer",
        about7:"I work with various technologies, including",
        about8:"Node, Python, Next, Nest, Django, React, React Native, and more.",
        about9:"With my knowledge, I create diverse features such as",
        about10:"Web Applications, Admin Panels, RESTful APIs, E-commerce Solutions, and Custom Software Development.",
        about11:"Besides coding, there are a few other activities that I love to engage in!",
        about12:"Building Side Projects",
        about13:"Learning New Technologies",
        about14:"Contributing to Open Source",
        about15:'"Always do your best!"',
        about16:"Professional",
        about17:"Skillset",
        about18:"Tools",
        about19:"I use",
        about20:"Days I",
        about21:"Code",
  
        projects:[
            {
                projects_image:iluy,
                projects_show:"Iluy.ai",
                projects_show_1:"Iluy is a multi AI assistant that allows you to use multiple AI models in one place.",
                projects_show_ghLink:"",
                projects_show_demoLink:"",
                projects_show_LiveLink:"https://iluy.ai/",
                highlight:true,
            },
            {
                projects_image:aorforms,
                projects_show:"Aorforms.com",
                projects_show_1:"Simplify Document Signing for Everyone. Aorforms is a platform that allows you to sign documents online.",
                projects_show_ghLink:"",
                projects_show_demoLink:"",
                projects_show_LiveLink:"https://aorforms.com/",
                highlight:true,
            },
            {
                projects_image:reboucasofficial,
                projects_show:"Rebouças University",
                projects_show_1:"Complete institutional platform with courses, institutional information, sales, enrollments, blogs, etc. Ideal for educational institutions.",
                projects_show_ghLink:"",
                projects_show_demoLink:"",
                projects_show_LiveLink:"https://faculdadereboucas.com.br/",
                highlight:true,
            },
            {
                projects_image:docstree,
                projects_show:"Docs-Tree",
                projects_show_1:"International and scalable platform for searching documents and freelancers. Ideal for startups and companies looking to grow in the digital realm.",
                projects_show_ghLink:"",
                projects_show_demoLink:"",
                projects_show_LiveLink:"",
                highlight:false,
            },
            {
                projects_image:shop,
                projects_show:"E-Commerce",
                projects_show_1:"Sales, promotions, shipping, marketing, gateway integrations, etc. Everything an e-commerce needs to grow.",
                projects_show_ghLink:"",
                projects_show_demoLink:"",
                projects_show_LiveLink:"",    
                highlight:false,    
            },
            {
                projects_image:hewantsbarber,
                projects_show:"He Wants Barber",
                projects_show_1:"Complete dashboard for sales, records, appointments, sales control, etc. Ideal for companies and self-employed individuals who work with appointments.",
                projects_show_ghLink:"",
                projects_show_demoLink:"",
                projects_show_LiveLink:"",        
            },
            {
                projects_image:pabloitalo,
                projects_show:"Personal portfolio",
                projects_show_1:"Landing and pages with information, contacts, and advertisements. Ideal for showcasing your work and specialties.",
                projects_show_ghLink:"https://github.com/pabloitaloac/pabloitalo.com",
                projects_show_demoLink:"",
                projects_show_LiveLink:"https://pabloitalo.com/",        
            },
            {
                projects_image:araujocabral,
                projects_show:"Institutional - Lawyer/Law Firm",
                projects_show_1:"Institutional website showcasing areas of practice, locations, specialties, the team involved, and much more. Ideal for lawyers and law firms looking to grow and stand out.",
                projects_show_ghLink:"",
                projects_show_demoLink:"",
                projects_show_LiveLink:"",        
            },
            {
                projects_image:personaltrainer,
                projects_show:"Personal Trainer Portfolio",
                projects_show_1:"Complete website with professional information, examples of sessions, and the ability to schedule appointments and sell plans. Ideal for those looking to expand their practice and attract new clients.",
                projects_show_ghLink:"",
                projects_show_demoLink:"",
                projects_show_LiveLink:"",        
            },
        ],


        resume1:'Download CV',
    },
    {
        language:'BR',
  
        navbar1:'Home',
        navbar2:'Sobre mim',
        navbar3:'Projetos',
        navbar4:'Currículo',
  
        footer1:'Desenvolvido com ❤️ por Pablo Ítalo',
        footer2:`Copyright © ${new Date().getFullYear()} Pablo Italo`,
  
        home1:'Olá!',
        home2:"Meu nome é",
        home3:"Sênior - Desenvolvedor Full Stack",
        home4:"Breve",
        home5:"INTRODUÇÃO",
        home6:"sobre mim",
        home7:"Sou apaixonado por programação e aprendi muito.",
        home8:"Tenho proficiência em linguagens e framworks modernos, como",
        home9:"Next.js, Nest.js, React, React Native, Node.js, Express, TypeScript, and JavaScript.",
        home10:"Além disso, também tenho experiência com Python, Django, PHP, WordPress, PostgreSQL, MongoDB, Redis, e mais.",
        home11:"Meu principal interesse é inovar e desenvolver",
        home12:"aplicações Web, Mobile, APIs, e etc.",
        home13:"ME ENCONTRE EM",
        home14:"Fique à vontade para se",
        home15:"conectar",
        home16:"comigo",
  
        about1:"Quem",
        about2:"eu seu",
        about3:"Olá, meu nome é",
        about4:"Pablo Ítalo",
        about5:", ",
        about6:"Engenheiro de Software Sênior",
        about7:"Trabalho com muitas tecnologias, incluindo",
        about8:"Node, Python, Next, Nest, Django, React, React Native, e mais.",
        about9:"Com meu conhecimento, crio diversas soluções, como",
        about10:"Aplicações Web, Painéis Administrativos, APIs RESTful, Soluções de E-commerce, e Desenvolvimento de Software Personalizado.",
        about11:"Além de codar, essas são outras atividades que eu amo fazer!",
        about12:"Construir Projetos",
        about13:"Aprender novas tecnologias",
        about14:"Contribuir para projetos open source",
        about15:'"Sempre dê o seu melhor!"',
        about16:"principais",
        about17:"Habilidades profissionais",
        about18:"Ferramentas",
        about19:"que utilizo",
        about20:"Dias que",
        about21:"Codo",
  
        projects1:'Meus recentes',
        projects2:'Trabalhos',
        projects3:"Esses são alguns dos projetos que desenvolvi recentemente.",

        projects:[
            {
                projects_image:iluy,
                projects_show:"Iluy.ai",
                projects_show_1:"Iluy é um assistente multi-IA que permite usar vários modelos de IA em um lugar só.",
                projects_show_ghLink:"",
                projects_show_demoLink:"",
                projects_show_LiveLink:"https://iluy.ai/",
                highlight:true,
            },
            {
                projects_image:aorforms,
                projects_show:"Aorforms.com",
                projects_show_1:"Simplifique a assinatura de documentos para todos. Aorforms é uma plataforma que permite assinar documentos online.",
                projects_show_ghLink:"",
                projects_show_demoLink:"",
                projects_show_LiveLink:"https://aorforms.com/",
                highlight:true,
            },
            {
                projects_image:reboucasofficial,
                projects_show:"Universidade Rebouças",
                projects_show_1:"Plataforma institucional completa com cursos, informações institucionais, vendas, matrículas, blogs e etc. Ideal para instituições de ensino.",
                projects_show_ghLink:"",
                projects_show_demoLink:"",
                projects_show_LiveLink:"https://faculdadereboucas.com.br/",
                highlight:true,
            },
            {
                projects_image:docstree,
                projects_show:"Docs-Tree",
                projects_show_1:"Plataforma internacional e escalável para buscar documentos e freelancers. Ideal para startups e empresas que buscam crescer no meio digital.",
                projects_show_ghLink:"",
                projects_show_demoLink:"",
                projects_show_LiveLink:"",
                highlight:false,
            },
            {
                projects_image:shop,
                projects_show:"Loja online",
                projects_show_1:"Vendas, promoções, fretes, marketing, integrações com gateway, etc. Tudo que um ecommerce precisa para crescer",
                projects_show_ghLink:"",
                projects_show_demoLink:"",
                projects_show_LiveLink:"",    
                highlight:false,    
            },
            {
                projects_image:hewantsbarber,
                projects_show:"He Wants Barber",
                projects_show_1:"Dashboard completa para vendas, registros, agendamentos, controle de vendas e etc. Ideal para empresas e autônomos que trabalham com agendamentos.",
                projects_show_ghLink:"",
                projects_show_demoLink:"",
                projects_show_LiveLink:"",        
            },
            {
                projects_image:pabloitalo,
                projects_show:"Portfólio pessoal",
                projects_show_1:"Landing e páginas com informações, contatos, e publicidades. Ideal para mostrar seu trabalho e especialidades.",
                projects_show_ghLink:"https://github.com/pabloitaloac/pabloitalo.com",
                projects_show_demoLink:"",
                projects_show_LiveLink:"https://pabloitalo.com/",        
            },
            {
                projects_image:araujocabral,
                projects_show:"Institucional - Advogado/escritório",
                projects_show_1:"Site institucional com mostragem de áreas de atuação, locais, especialidades, time envolvido e muito mais. Ideal para advogados e escritórios que buscam crescer e se destacar.",
                projects_show_ghLink:"",
                projects_show_demoLink:"",
                projects_show_LiveLink:"",        
            },
            {
                projects_image:personaltrainer,
                projects_show:"Portfólio Personal Trainer",
                projects_show_1:"Website completo com informações profissionais, exemplo de atendimentos, e com possibilidade de agendamento e vendas de planos. Ideal para quem busca ampliar sua atuação e buscar novos clientes.",
                projects_show_ghLink:"",
                projects_show_demoLink:"",
                projects_show_LiveLink:"",        
            },
        ],

        resume1:'Baixar currículo',
  
    },
  ]
  

