name: AUTO UPDATE PROD WITH THE MAIN - pabloitalo frontend prod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, production]
    
    steps:
      - name: grant permissions to runners
        run: |
          sudo chmod -R 777 /home/pabloitalo
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Remove any trash
        run: |
          docker system prune -a --volumes --force

      - name: Check if network exists
        run: |
          if ! docker network ls --format '{{.Name}}' | grep -q '^network_pabloitalo_prod$'; then
            echo "Network does not exist, creating it."
            docker network create network_pabloitalo_prod
          else
            echo "Network exists."
          fi

      - name: Check if container exists
        id: check_container
        run: |
          if docker ps -a --format '{{.Names}}' | grep -q '^pabloitalo_frontend_prod$'; then
            echo "Container exists"
            docker-compose -f docker-compose.prod.yml down --volumes --remove-orphans            
          else
            echo "Container does not exist"         
          fi

      - name: Start container
        run: |
          docker-compose -f docker-compose.prod.yml -p pabloitalo_frontend_prod up --build -d
          docker system prune -a --volumes --force
          
      - name: Check if container nginx exists
        run: |
          if docker ps -a --format '{{.Names}}' | grep -q '^nginx$'; then
            echo "Container exists"
            docker restart nginx
          else
            echo "Container does not exist"
          fi

      - name: Check if container traefik exists
        run: |
          if docker ps -a --format '{{.Names}}' | grep -q '^traefik$'; then
            echo "Container exists"
            docker restart traefik
          else
            echo "Container does not exist"
          fi
